import { ProjectNav } from '../project-nav';
import type { Metadata } from 'next';
import '../ryusei-wave/wave.css';
import './summer.css';
export const dynamic = 'force-static';
export const metadata: Metadata={title:'夏の存在証明 — Sound Experiment',description:'音を重ねて、自分の夏をつくる。夏に耳にする音を選び、重ねて聴ける共同制作作品。'};
export default function Summer(){return <div className="wave-case summer-case"><a className="skip" href="#overview">本文へ移動</a><header className="site-header" id="top"><a className="wordmark" href="/">Portfolio<span className="wordmark-dot">.</span></a><span className="header-caption">PORTFOLIO / EXPERIMENT 06</span><a className="header-link" href="/lens">07 — Lens ↗</a></header><main>
<section className="hero wrap"><div className="eyebrow hero-eyebrow"><span>SOUND / INTERACTION EXPERIMENT</span><span>2025</span></div><div className="title-row"><h1>夏の存在証明</h1><p className="wave-tagline">音を重ねて、自分の夏をつくる。</p></div><figure><a className="summer-photo summer-hero" href="/assets/summer/screen.png" target="_blank" rel="noreferrer" aria-label="作品の展示記録を拡大"><img src="/assets/summer/screen.png" width={4012} height={9280} alt="青空と雲を背景に音の操作画面を表示したタブレット" fetchPriority="high"/></a><figcaption>夏の存在証明 — タブレットでの展示。</figcaption></figure></section>
<section className="wrap wave-about" id="overview"><p className="body-copy">形はないのに、確かに感じる夏の存在感に惹かれて。夏に耳にする音を選び、重ねながら、自分の思い浮かべる夏をつくる作品です。</p><dl className="metadata"><div><dt>DATE</dt><dd>2025.08</dd></div><div><dt>MY ROLE</dt><dd>Aino Kishimoto<br/>アイデア・UI/UXデザイン</dd></div><div><dt>COLLABORATOR</dt><dd>Shuhey Koyama<br/>実装</dd></div><div><dt>TYPE</dt><dd>共同制作<br/>Sound / Interaction</dd></div></dl></section>
<section className="wrap wave-exhibition"><div className="wave-exhibition-heading"><span className="eyebrow">INTERACTION</span><p>音を選ぶ → 重ねる → 組み合わせて聴く</p></div><div className="summer-gallery"><figure><a className="summer-photo summer-operation" href="/assets/summer/screen.png" target="_blank" rel="noreferrer" aria-label="音の操作画面の写真を拡大"><img src="/assets/summer/screen.png" width={4012} height={9280} alt="タブレット上で音のコントロールを操作する手元" loading="lazy"/></a><figcaption>画面を操作して、音を組み合わせる。</figcaption></figure><figure><a className="summer-photo summer-visitors" href="/assets/summer/screen.png" target="_blank" rel="noreferrer" aria-label="展示で作品に触れる様子を拡大"><img src="/assets/summer/screen.png" width={4012} height={9280} alt="展示されたタブレットの画面に触れる来場者" loading="lazy"/></a><figcaption>展示で作品に触れる様子。</figcaption></figure></div></section><section className="project-switch wrap"><span className="eyebrow">NEXT PROJECT / 07</span><a href="/lens"><span>Lens</span><span aria-hidden="true">↗</span></a><p>まだ知らない自分を、未来の絵日記から。</p></section><ProjectNav current="/summer"/></main><footer className="wrap"><a className="footer-title" href="/rain-clock">雨粒時計<span aria-hidden="true">↗</span></a><div><span>PREVIOUS PROJECT / 05</span><a href="#top">ページの先頭へ ↑</a></div></footer></div>}
