import { ProjectNav } from '../project-nav';
import Image from "next/image";
import type { Metadata } from 'next';
export const dynamic = 'force-static';
export const metadata: Metadata = { title: 'Knitted VJ System — 計算機に、人間のやわらかさを。', description: '糸を編む行為から映像を生むライブシステム。構想からTOKYO NODEでの本番運用まで、約1週間。' };
function Label({n,children}:{n:string;children:React.ReactNode}){return <div className="section-label"><span>{n}</span><span>{children}</span></div>}
function Caption({no,children}:{no:string;children:React.ReactNode}){return <figcaption><span className="figure-no">FIG. {no}</span><span>{children}</span></figcaption>}
const imageSizes:Record<string,[number,number]>={"performance-sketch":[4032,3024],"interaction-sketch":[3024,4032],exhibition:[1500,2000],hands:[1333,2000],interface:[2000,1824],live:[1333,2000],material:[2000,1333],skin:[844,562],system:[2000,1333],touchdesigner:[2000,1187]};
function Photo({name,alt}:{name:string;alt:string}){const [width,height]=imageSizes[name];return <Image unoptimized src={`/assets/knitted/${name}.webp`} width={width} height={height} alt={alt} loading="lazy"/>}
function Marker({n,children}:{n:string;children:React.ReactNode}){return <div className="point-marker"><span className="point-number">{n}</span><span className="eyebrow">{children}</span></div>}
function Capabilities({items}:{items:string[]}){return <div className="capabilities">{items.map(item=><span key={item}>{item}</span>)}</div>}
export default function KnittedCaseStudy() { return <div className="knitted-case">
<a className="skip" href="#main-content">本文へ移動</a>
<header className="site-header" id="top"><a className="wordmark" href="/">Portfolio<span className="wordmark-dot">.</span></a><span className="header-caption">PORTFOLIO / CASE STUDY 02</span><a className="header-link" href="/nnamuimonyo">03 — 編みスクリーン <span aria-hidden="true">↗</span></a></header>
<main id="main-content"><section className="hero wrap knitted-hero" aria-labelledby="project-title"><div className="eyebrow hero-eyebrow"><span>MATERIAL × COMPUTATION</span><span>2026</span></div><div className="title-row"><h1 id="project-title">Knitted<br/><em>VJ System</em></h1><div className="hero-category">Realtime Visual<br/>Interaction Design<span>LIVE PERFORMANCE</span></div></div><div className="knitted-hero-intro"><p>糸を編む行為から映像を生むライブシステム。</p></div><figure><div className="knitted-hero-photo"><Image unoptimized width={4000} height={6000} src="/assets/knitted/live-original.webp" alt="白いニットをまとい、糸を張った装置を操作する演者と、背後に広がる生成映像" fetchPriority="high"/><a href="#output" className="hero-film-link"><span className="play-small" aria-hidden="true">▶</span>LIVE FILM <span aria-hidden="true">↘</span></a></div><figcaption><span className="figure-no">FIG. 01</span><span>Knitted VJ System — Scratch&Build in TOKYO NODE</span></figcaption></figure></section>
<section className="overview wrap section-grid" id="overview"><div className="section-label"><span>01</span><span>OVERVIEW</span></div><div><p className="intro">糸を編むと色・線・形が生まれ、音に応じて伸び、広がっていくライブシステム。私はInteractionの構想、TouchDesignerによる映像生成の設計・実装、VJを担当。機材・衣装・音楽の専門家と協働し、約1週間でTOKYO NODEでの本番運用まで進めました。</p><p className="body-copy">映像生成・VJ：私 ／ 機材・入力系：Shuhey Koyama ／ 衣装：TackT ／ DJ：jungjieyun</p><a className="knitted-inline-link" href="#output">本番の映像を見る ↓</a><dl className="metadata"><div><dt>DATE / DURATION</dt><dd>2026.03.22<br/>約1週間</dd></div><div><dt>ROLE</dt><dd>Concept / Interaction Design<br/>TouchDesigner / VJ</dd></div><div><dt>FIELD</dt><dd>Material Interaction<br/>Realtime Visual</dd></div><div><dt>CONTEXT</dt><dd>Scratch&Build<br/>in TOKYO NODE</dd></div></dl></div></section>
<nav className="chapter-nav wrap" aria-label="ページ内の目次"><span className="eyebrow">IN THIS PROJECT</span><div><a href="#aim">プロジェクトの目的</a><a href="#contributions">3つの取り組み</a><a href="#output">アウトプット</a><a href="#reflection">振り返り</a></div></nav>
<section className="aim wrap section-grid section-space" id="aim"><Label n="02">PROJECT AIM</Label><div><p className="english-heading">Bringing human softness<br/><em>into computation.</em></p><h2>感性や記憶、手触りを、<br/>計算機の世界へ。</h2><p className="body-copy lead-copy">触れたときの感覚。身体に残る記憶。素材の柔らかさ。そうした人間の感覚を、計算機に宿したいと考えました。</p><p className="body-copy">『攻殻機動隊』が描く、身体とテクノロジー、記憶や自己をめぐる世界観にも、自身の関心を重ねています。身体を衣服で表現し、その素材を計算機につなぐことで、身体と情報の境界を探ろうとしました。</p><p className="body-copy">起点にしたのは、セーターをほどき、再び編む行為です。身体を包んでいた編み目が一本の糸に戻り、手を通して別の構造へ変わっていく。その過程を、自身の細胞や記憶に重ねました。</p><p className="body-copy">身体を包んでいた素材が、映像を生むきっかけになる。糸への働きかけをセンシングし、身体・素材・生成映像をつなぐ仕組みを構想しました。</p><figure className="knitted-sketch knitted-performance-sketch"><span className="eyebrow">CONCEPT SKETCH / 構想段階のラフ</span><a href="/assets/knitted/performance-sketch.webp" target="_blank" rel="noreferrer" aria-label="パフォーマンス全体の構想スケッチを拡大"><Photo name="performance-sketch" alt="演者、編み物の装置、PCの配置と、身体や情報について書き込んだ手描きの構想スケッチ"/><span className="source-expand">スケッチを拡大 ↗</span></a><Caption no="02">身体・編む行為・機材を、一つのパフォーマンスとして考えたラフ。</Caption></figure><aside className="concept-note"><span className="eyebrow">CONCEPT NOTE / 制作を振り返って</span><p>触覚は、胎内から発達する最も早い感覚の一つです。人が身体を通して周囲に触れるように、計算機にも素材と接する入口をつくる。この視点からも、今回の制作を捉えています。</p><a href="https://pmc.ncbi.nlm.nih.gov/articles/PMC5974044/" target="_blank" rel="noreferrer">参考文献 ↗</a></aside></div></section>
<section className="knitted-context wrap"><figure><Photo name="exhibition" alt="TOKYO NODEの展示空間に掲示された攻殻機動隊のビジュアル"/><Caption no="03">攻殻機動隊展 Ghost and the Shell — 会場の風景。</Caption></figure><div><span className="eyebrow">EXHIBITION CONTEXT</span><h2>攻殻機動隊の世界で、<br/>未来のクラフトを実践する。</h2><p className="body-copy">『攻殻機動隊展 Ghost and the Shell』は、アニメ制作30周年を記念し、歴代アニメシリーズを横断して紹介する大規模展覧会。TOKYO NODEで、1,000点以上の制作資料や体験型展示、現代クリエイターによるインスタレーションを通して、その世界を展開しました。</p><p className="body-copy">会期中の「電脳夜市」は、「未来のクラフト」をテーマに、トーク、マルシェ、Audio Visualライブが集まるイベント。その一つである「Scratch&Build」では、独自のソフトウェアやハードウェアを用い、音と映像をその場で構築する即興パフォーマンスが行われました。</p><div className="source-links"><a href="https://www.tokyonode.jp/sp/exhibition-ghostintheshell/" target="_blank" rel="noreferrer">展覧会公式サイト ↗</a><a href="https://www.tokyonode.jp/sp/exhibition-ghostintheshell/event/dialogue17/" target="_blank" rel="noreferrer">電脳夜市 / Scratch&Build ↗</a></div><div className="mission"><span className="eyebrow">MY MISSION</span><p>編む行為と生成映像をつなぐ体験を構想し、自ら映像を制作する。必要な専門家と協働し、約1週間で本番運用できるライブシステムにすることを目指しました。</p></div></div></section>
<div className="knitted-interlude wrap"><figure><Photo name="interface" alt="ニットをまとった演者の手、糸、センサーと配線が同じ画面に重なる"/><Caption no="04">身体と素材、計算機が接する場所。</Caption></figure></div>
<section className="contributions" id="contributions"><div className="contribution-heading wrap"><span className="eyebrow">MY CONTRIBUTIONS</span><h2>感覚を実装する、<br/><span>3つの取り組み。</span></h2><span className="contribution-total">01 — 03</span></div>
<article className="contribution wrap section-grid" id="material"><Marker n="01">MATERIAL AS<br/>INTERFACE</Marker><div><h2>衣服を身体に、<br/>編む行為を入力に。</h2><p className="body-copy">衣服を通して、身体そのものを表現したいと考えました。初期に構想したのは、肌に密着し、身体の輪郭が現れるタイツ姿です。身体に最も近い衣服を、もう一つの身体として捉えました。</p><p className="body-copy">実際に着用したタイツには、意図的に破れをつくっています。身体を覆う布と、そこから露出する肌。衣服と身体の境界を、衣装の表現に取り入れました。</p><div className="knitted-material-pair"><figure><Photo name="material" alt="毛羽立った白いニットの袖から現れる手と編み針"/><Caption no="05">身体を包むニットと、編む手。</Caption></figure><figure><Photo name="skin" alt="意図的に破れをつくったタイツと、切れ目から見える肌"/><Caption no="06">布と肌の境界を表現したタイツ。</Caption></figure></div><h3 className="knitted-subheading">ほどいても、素材は残る。<br/>編むことで、別の形になる。</h3><p className="body-copy">編む行為には、糸の抵抗を感じながら、指先の力や動きを調整する身体的なやり取りがあります。TackTが3日間で制作したニットをまとい、セーターをほどいた糸を装置へ編み込む。その働きかけを、映像への入力につなげました。</p><figure className="knitted-signal"><span className="eyebrow">INTERACTION STRUCTURE</span><ol>{['手の操作','糸の張力','ロードセル','Arduino','TouchDesigner','生成映像'].map((step,i)=><li key={step}><span className="signal-index">{String(i+1).padStart(2,'0')}</span><span>{step}</span>{i<5&&<span className="signal-arrow" aria-hidden="true">→</span>}</li>)}</ol><Caption no="07">糸を引く力を計測し、映像へつなぐ入力の流れ。</Caption></figure><p className="body-copy">糸を引く力をロードセルで計測し、Arduinoを介してTouchDesignerへ入力。素材の物理的な変化を、映像に働きかける操作として扱っています。</p><Capabilities items={['MATERIAL INTERACTION','EMBODIED INTERACTION','CONCEPT DEVELOPMENT']}/></div></article>
<article className="contribution wrap section-grid" id="visual"><Marker n="02">REALTIME<br/>VISUAL SYSTEM</Marker><div><h2>糸が映像を生み、<br/>音がその後を動かす。</h2><p className="ownership-statement">映像の生成・連なり・変形・消失までを設計し、TouchDesignerで実装。</p><p className="body-copy">糸の張力が設定した閾値を超えると、色・線・形が生成されます。今回は張力の強弱を連続値として扱わず、入力の有無を判定する0／1の構造としました。</p><p className="body-copy">糸の操作を映像が生まれる契機とし、音をその後の展開に割り当てています。音楽からビートに関わる周波数帯を取得し、生成された形が伸び、広がりながら、線や色を変えるように設計しました。</p><p className="body-copy">一度生まれた形はすぐに消えず、ゆっくりと減衰します。編み続けると新しく生まれた線が前の線につながり、映像の中でも糸が連なって伸びていきます。</p><figure className="knitted-sketch knitted-interaction-sketch"><span className="eyebrow">INTERACTION STUDY / 入力と映像の検討</span><a href="/assets/knitted/interaction-sketch.webp" target="_blank" rel="noreferrer" aria-label="入力と数値の関係を検討したスケッチを拡大"><Photo name="interaction-sketch" alt="H1からH4、V1からV4の格子と、0.00から1.00の値、映像と記した表を描いた手書きの検討スケッチ"/><span className="source-expand">スケッチを拡大 ↗</span></a><Caption no="08">格子・数値・映像の関係を検討した構想段階のスケッチ。</Caption></figure><div className="knitted-mapping"><span className="eyebrow">INTERACTION MAPPING</span><div><span>張力が閾値を超える</span><span aria-hidden="true">→</span><strong>色・線・形が現れる</strong></div><div><span>糸を編み続ける</span><span aria-hidden="true">→</span><strong>線が連なり、伸びる</strong></div><div><span>音のビートに反応する</span><span aria-hidden="true">→</span><strong>形が伸び、広がり、変化する</strong></div><div><span>時間が経過する</span><span aria-hidden="true">→</span><strong>生成された形がゆっくり消える</strong></div></div><figure className="knitted-network"><a href="/assets/knitted/touchdesigner.webp" target="_blank" rel="noreferrer" aria-label="TouchDesignerの制作画面を拡大"><Photo name="touchdesigner" alt="TouchDesignerの制作画面。映像生成のノードとパラメータ、出力が表示されている"/><span className="source-expand">制作画面を拡大 ↗</span></a><Caption no="09">TouchDesignerの映像制作画面。</Caption></figure><p className="body-copy">センサー受信・数値調整・映像パラメータへの接続はShuhey Koyamaが担当。私は接続先となる映像生成部分と、その後の振る舞いを制作しました。</p><a className="knitted-inline-link" href="#output">手元と出力映像を見る ↓</a><Capabilities items={['REALTIME PROTOTYPING','VISUAL SYSTEM DESIGN','TOUCHDESIGNER']}/></div></article>
<article className="contribution wrap section-grid" id="live-production"><Marker n="03">FROM CONCEPT<br/>TO LIVE</Marker><div><h2>成立させる範囲を決め、<br/>約1週間でライブへ。</h2><p className="body-copy">限られた期間で本番へ持ち込むため、操作機材には製作しやすく、センサーを固定しやすい四角形のフレームを採用しました。</p><p className="body-copy">張力の強弱を連続的に映像へ反映する案もありましたが、今回は閾値を超えたかを判定する構造に絞り、「糸を編むことで映像が生まれる」という関係を本番で成立させることを優先しました。連続値による表現は次の検証項目としています。</p><p className="body-copy">Shuhey Koyamaと操作機材のアイデアを検討し、機材制作と入力系の実装を依頼。私はコンセプトと映像制作を担い、衣装を担当するTackT、DJのjungjieyunとともに準備を進めました。</p><div className="knitted-duration"><span className="eyebrow">FROM CONCEPT TO LIVE</span><p>約<span>1</span>週間</p><span>構想・映像制作・協働・本番運用</span></div><figure className="knitted-system-photo"><Photo name="system" alt="四角形のフレームに糸とセンサーを配置した機材と、その前に広がる白いニット"/><Caption no="10">製作とセンサー固定のしやすさから選んだ四角形のフレーム。機材制作：Shuhey Koyama。</Caption></figure><Capabilities items={['RAPID PROTOTYPING','SCOPE DEFINITION','LIVE PRODUCTION']}/></div></article></section>
<section className="output-section knitted-output" id="output"><div className="wrap"><div className="output-heading"><Label n="06">OUTPUT</Label><div><p className="english-heading">From material.<br/><em>To moving image.</em></p><h2>TOKYO NODEでのライブパフォーマンス</h2><p className="body-copy">2026年3月22日、TOKYO NODEで開催された「電脳夜市／Scratch&Build」で本番運用しました。</p></div></div><div className="knitted-film-guide"><h3>映像を見るポイント</h3><p>糸の張力が閾値を超えると色・線・形が生まれ、音に応じて伸びたり広がったりしながら、時間とともに消えていきます。</p><p>私はこの映像生成と振る舞いをTouchDesignerで実装し、本番のVJを担当しました。センサー受信・数値調整・映像への接続は共同制作者が担当しています。</p><a className="knitted-inline-link" href="#visual">入力と映像の対応・制作画面を見る ↑</a></div><div className="knitted-input-output"><figure><span className="eyebrow">01 / PHYSICAL INPUT</span><Photo name="hands" alt="フレームに張った糸を両手で編み込む操作の接写"/><Caption no="11">糸を編み込む、手元の操作。</Caption></figure><figure><span className="eyebrow">02 / LIVE VISUAL OUTPUT</span><video controls playsInline preload="none" poster="/assets/knitted/video-poster.webp" aria-label="Knitted VJ Systemのライブ映像。糸の操作と音に応じて色や形が変化する"><source src="/assets/knitted/live.mp4" type="video/mp4"/><track kind="captions" src="/assets/knitted/live-description.vtt" srcLang="ja" label="映像の説明"/>お使いのブラウザでは動画を再生できません。映像を再生できない場合は、下のリンクから開いてください。</video><Caption no="12">本番の生成映像。音声付き・約24秒。</Caption><a href="/assets/knitted/live.mp4" className="knitted-inline-link" target="_blank" rel="noreferrer">映像を別タブで開く ↗</a></figure></div><p className="knitted-media-note">手元写真と動画は、入力と出力の関係を示す別々の記録です。</p></div></section>
<section className="reflection wrap section-grid section-space" id="reflection"><Label n="07">REFLECTION</Label><div><h2>計算機に、<br/>人間のやわらかさを。</h2><p className="body-copy">本番では、映像の形が速く変わるのを見て、編む速度を落とす場面がありました。糸に触れて映像を変え、その映像に自分の手の動きも影響される。制作した仕組みは、演じる身体にも働きかけていました。</p><div className="reflection-line">Bringing human softness<br/><em>into computation.</em></div></div></section>
<section className="credits wrap section-grid"><Label n="08">ROLE / CREDITS</Label><div><div className="credits-heading"><h2>私の担当</h2><span>Concept / Visual / VJ</span></div><ul>{['コンセプト開発','Interactionの構想・設計','リアルタイム映像の振る舞いの設計','TouchDesignerによる映像生成の実装','VJパフォーマンス','素材・衣装のコンセプト','操作機材の共同アイデア検討','制作調整'].map((role,i)=><li key={role}><span>{String(i+1).padStart(2,'0')}</span>{role}</li>)}</ul><h3 className="knitted-subheading">共同制作者</h3><dl className="knitted-collaborators"><div><dt>DJ</dt><dd>jungjieyun</dd></div><div><dt>衣装</dt><dd>TackT</dd></div><div><dt>Technical Support</dt><dd>Shuhey Koyama<span>機材制作／センサー受信／数値調整／映像パラメータへの接続</span></dd></div></dl><p className="credit-note">掲載するライブは、上記の役割分担による共同制作の成果です。</p></div></section>
<section className="project-switch wrap"><span className="eyebrow">NEXT PROJECT / 03</span><a href="/nnamuimonyo"><span>編みスクリーン</span><span aria-hidden="true">↗</span></a><p>暮らしの思想 — 感覚的な質を、設計できるものにする。</p></section><ProjectNav current="/knitted-vj-system"/></main><footer className="wrap"><a className="footer-title" href="/x-couture">X <em>couture</em><span aria-hidden="true">↗</span></a><div><span>PREVIOUS PROJECT / 01</span><a href="#top">ページの先頭へ ↑</a></div></footer></div>; }
