import { ProjectNav } from '../project-nav';
import type { Metadata } from 'next';
import './wave.css';
export const dynamic = 'force-static';
export const metadata: Metadata = {title:'Ryusei Wave — Creative Coding',description:'点の集まりが形を変え続け、星にも魚の群れにも見える映像。知覚が像を補完する曖昧な表現をp5.jsで制作。'};
export default function RyuseiWave(){return <div className="wave-case">
<a className="skip" href="#overview">本文へ移動</a>
<header className="site-header" id="top"><a className="wordmark" href="/">Portfolio<span className="wordmark-dot">.</span></a><span className="header-caption">PORTFOLIO / EXPERIMENT 04</span><a className="header-link" href="/rain-clock">05 — 雨粒時計 ↗</a></header>
<main>
<section className="hero wrap"><div className="eyebrow hero-eyebrow"><span>CREATIVE CODING / EXPERIMENT</span><span>2025</span></div><div className="title-row"><h1>Ryusei <em>Wave</em></h1><p className="wave-tagline">星にも、魚の群れにも見える波。</p></div><figure><div className="wave-hero-image"><img src="/assets/ryusei-wave/exhibition-original.png" alt="夜の二子玉川ライズ。3つのLEDキューブにピンクや水色の点が浮かぶ" fetchPriority="high"/></div><figcaption>Ryusei Wave — 二子玉川ライズでの展示風景。</figcaption></figure></section>
<section className="wrap wave-about" id="overview"><p className="body-copy">点の集まりが形を変え続けることで、空の星にも、海を泳ぐ魚の群れにも見える映像を制作しました。具体的な形を描き切らず、動きと配置に曖昧さを残すことで、見る人の知覚が像を補完する表現を探りました。p5.jsで映像を実装し、二子玉川ライズの3連LEDキューブへ展開しました。</p><p className="wave-keywords">Visual Ambiguity / Motion / Creative Coding</p><dl className="metadata"><div><dt>DATE</dt><dd>2025.08</dd></div><div><dt>ROLE / AINO KISHIMOTO</dt><dd>コンセプト・映像・コーディング</dd></div><div><dt>TOOLS</dt><dd>p5.js / AI</dd></div><div><dt>CONTEXT</dt><dd>NEORT 2025 / 二子玉川ライズ</dd></div></dl></section>
<section className="wrap wave-exhibition"><div className="wave-exhibition-heading"><span className="eyebrow">EXHIBITION</span><p>2025年8月、二子玉川ライズの3連LEDキューブで展示しました。</p></div><div className="wave-gallery"><figure><a className="wave-crop wave-day" href="/assets/ryusei-wave/work.png" target="_blank" rel="noreferrer" aria-label="昼の展示記録を拡大"><img src="/assets/ryusei-wave/work.png" alt="昼の3連LEDキューブの全景" loading="lazy"/></a><figcaption>昼の展示風景。</figcaption></figure><figure><a className="wave-crop wave-night" href="/assets/ryusei-wave/work.png" target="_blank" rel="noreferrer" aria-label="夜の展示記録を拡大"><img src="/assets/ryusei-wave/work.png" alt="夜のLEDキューブと周囲の街並み" loading="lazy"/></a><figcaption>夜の展示風景。</figcaption></figure><figure><a className="wave-crop wave-detail" href="/assets/ryusei-wave/work.png" target="_blank" rel="noreferrer" aria-label="キューブの近景を拡大"><img src="/assets/ryusei-wave/work.png" alt="下から見上げたキューブの映像" loading="lazy"/></a><figcaption>キューブの近景。</figcaption></figure></div></section>
<section className="project-switch wrap"><span className="eyebrow">NEXT PROJECT / 05</span><a href="/rain-clock"><span>雨粒時計</span><span aria-hidden="true">↗</span></a><p>一滴の雨から、空との距離を捉え直す。</p></section><ProjectNav current="/ryusei-wave"/></main><footer className="wrap"><a className="footer-title" href="/nnamuimonyo">編みスクリーン<span aria-hidden="true">↗</span></a><div><span>PREVIOUS PROJECT / 03</span><a href="#top">ページの先頭へ ↑</a></div></footer></div>}
