import { ProjectNav } from '../project-nav';
import type { Metadata } from 'next';
import './study.css';

export const dynamic = 'force-static';

export const metadata: Metadata = {
 title: '編みスクリーン — nnamuimonyo / 暮らしの思想',
 description: 'フィッシャーマンズリブの構造から色の見え方を変える画面を探索。仮説立案・制作依頼・試作確認から、川や花に見立てた展示へ展開しました。',
};
const asset = '/assets/nnamuimonyo/';
function Label({n,children}:{n:string;children:React.ReactNode}){return <div className="section-label"><span>{n}</span><span>{children}</span></div>}
function Evidence({src,alt,width,height,no,children}:{src:string;alt:string;width:number;height:number;no:string;children:React.ReactNode}){return <figure className="study-evidence"><a href={`${asset}${src}`} target="_blank" rel="noreferrer" aria-label={`${alt}を拡大`}><img src={`${asset}${src}`} width={width} height={height} alt={alt} loading="lazy"/><span className="source-expand">資料を拡大 ↗</span></a><figcaption><span className="figure-no">FIG. {no}</span><span>{children}</span></figcaption></figure>}
const roles=['編みスクリーンのアイデア提案・見え方の仮説立案','共同制作者への制作依頼・試作の確認','展示の企画・空間のテーマ設計','編み花の動きのアイデア提案','空間装飾の一部'];
export default function MaterialStudy(){return <div className="material-study">
<a className="skip" href="#overview">本文へ移動</a><header className="site-header" id="top"><a className="wordmark" href="/">Portfolio<span className="wordmark-dot">.</span></a><span className="header-caption">PORTFOLIO / CASE STUDY 03</span><a className="header-link" href="/ryusei-wave">04 — Ryusei Wave ↗</a></header><main>
<section className="wrap material-hero screen-hero" aria-labelledby="project-title"><div className="eyebrow hero-eyebrow"><span>MATERIAL EXPLORATION / EXHIBITION</span><span>03</span></div><h1 id="project-title">編みスクリーン<span>nnamuimonyo / 暮らしの思想</span></h1><p className="study-category">Concept Development / Material Exploration / Exhibition</p><figure className="screen-hero-photo"><img src={`${asset}display-texture.jpg`} width={1206} height={1650} alt="青と水色の編み地。糸の太さ、編み目と立体的な質感" fetchPriority="high"/><figcaption>編みスクリーンの編み地。</figcaption></figure></section>
<section className="wrap section-grid overview" id="overview"><Label n="01">OVERVIEW</Label><div><p className="intro">フィッシャーマンズリブの畝と谷を使い、編み地の変形で色の見え方を変えるスクリーンの探索。私はアイデア提案、見え方の仮説立案、制作依頼・試作確認を担当。狙った表示には至らなかったものの、素材の条件に課題を見いだし、4人での展示へ展開しました。</p><dl className="metadata"><div><dt>PERIOD</dt><dd>2026.07.26–08.01</dd></div><div><dt>ROLE</dt><dd>企画・仮説立案<br/>制作依頼・試作確認</dd></div><div><dt>TEAM</dt><dd>4人による共同制作</dd></div><div><dt>CONTEXT</dt><dd>nnamuimonyo展<br/>暮らしの思想</dd></div></dl></div></section>
<nav className="chapter-nav wrap" aria-label="ページ内の目次"><span className="eyebrow">IN THIS PROJECT</span><div><a href="#aim">目的</a><a href="#contributions">私の取り組み</a><a href="#findings">試作結果</a><a href="#exhibition">展示への展開</a><a href="#reflection">振り返り</a></div></nav>
<section className="wrap section-grid section-space" id="aim"><Label n="02">PROJECT AIM</Label><div><h2>画面そのものが、質感を持ち、<br/>柔らかく変化する。</h2><p className="body-copy">画面を見て、柔らかさやざらつきを想像することがあります。その視覚的な印象が、実際の手触りや厚みを伴っていたら、画面との関わり方はどう変わるのか。</p><p className="body-copy">色や模様を表示する面そのものを、糸と編み構造でつくろうと考えました。</p><p className="body-copy">見るだけでは分からない伸びや抵抗があり、力を加えることで形と見え方が変わる。<strong>素材に働きかけることと、視覚情報が変わることをつなぐ画面</strong>を探りました。</p><div className="mission"><span className="eyebrow">MY MISSION</span><p>見え方のアイデアを、素材のどこをどう変えるかという仮説へ具体化し、共同制作者と実物で確かめること。</p></div></div></section>
<section className="contributions" id="contributions"><div className="contribution-heading wrap"><span className="eyebrow">03 / MY CONTRIBUTIONS</span><h2>私の取り組み</h2><span className="contribution-total">01 — 02</span></div>
<article className="contribution wrap section-grid"><div className="point-marker"><span className="point-number">01</span><span className="eyebrow">MATERIAL STRUCTURE</span></div><div><h2>編み地の立体構造を、<br/>色の変化に使う。</h2><p className="body-copy">着目したのは、フィッシャーマンズリブの、畝（うね）と谷が並ぶ立体的な編み構造です。</p><p className="body-copy">編み地を引くことで畝の間が広がり、谷側の色が現れる。その変化を使えば、見える色の割合を変え、画面が揺らぐように表現できるのではないかと考えました。</p><figure className="study-connection"><span className="eyebrow">DESIGN HYPOTHESIS / 狙った変化</span><ol>{['編み地を引く','畝の間が広がる','谷側の色が現れる','見える色の割合が変わる'].map((step,i)=><li key={step}><span className="eyebrow">0{i+1}</span><span>{step}</span></li>)}</ol></figure></div></article>
<article className="contribution wrap section-grid"><div className="point-marker"><span className="point-number">02</span><span className="eyebrow">PRODUCTION BRIEF & REVIEW</span></div><div><h2>見え方の仮説を共有し、<br/>制作を依頼する。</h2><p className="body-copy">初期にはWeb上で見え方のイメージを確認し、実物の編み地で表現する方法を検討しました。</p><p className="body-copy">成立条件として整理したのは、次の2点です。</p><ul className="screen-criteria"><li>模様が切り替わることが分かること</li><li>切り替えに、編み物の構造を利用していること</li></ul><p className="body-copy">私は実現したい表現と見え方の仮説を共同制作者へ伝え、制作を依頼。制作された実物が、意図した表現につながっているかを確認しました。</p><Evidence src="requirements.png" width={1690} height={1714} no="01" alt="編みスクリーンと編み花の成立条件・技術候補をまとめた資料">右側が編みスクリーンの検討資料。「模様の切り替わり」と「編み構造の利用」を成立条件に設定。技術候補は検討段階のものです。</Evidence></div></article>
</section>
<section className="wrap section-grid section-space" id="findings"><Label n="04">PROTOTYPE / FINDINGS</Label><div><h2>色の切り替わりは、<br/>十分に現れなかった。</h2><Evidence src="display-touch.jpg" width={2364} height={1773} no="02" alt="書棚に設置された編みスクリーンの全体と、編み地に触れる来場者">実物の編みスクリーン。写真は展示の記録で、色の切り替わりを示すものではありません。</Evidence><p className="body-copy">試作では、狙った色や模様の切り替わりを十分に表現できず、ディスプレイのような見え方には至りませんでした。</p><p className="body-copy">糸の太さ、編み地の緩さ、畝の立ち上がりが影響したと考えています。ただし、それぞれの条件を切り分けて比較していないため、原因の特定には至っていません。</p><p className="body-copy">この結果から、動かす機構だけでなく、<strong>変形したときに何が見えるかを、糸・編み方・張り方まで含めて検討する必要がある</strong>と考えました。</p></div></section>
<section className="screen-exhibition" id="exhibition"><section className="wrap section-grid section-space" id="exhibition-intro"><Label n="05">EXHIBITION</Label><div><h2>空想と現実が、<br/>地続きに交わる展示。</h2><p className="body-copy">編みスクリーンを川に見立て、動く編み花とともに展示しました。身近な素材をいつもと異なる姿で見せ、日常の質感やふるまいを捉え直すきっかけを目指しました。</p><p className="body-copy">私は空間のテーマ設計と編み花の動きのアイデアを提案し、装飾の一部を担当しました。</p></div></section><div className="wrap screen-wide-evidence"><Evidence src="exhibition-wide.jpg" width={2364} height={1773} no="03" alt="川に見立てた編み地と花が並ぶ展示全景">編みスクリーンと編み花を組み合わせた展示空間。</Evidence></div><div className="wrap screen-flower-record screen-exhibition-media"><Evidence src="display-hanging.jpg" width={1204} height={1606} no="04" alt="壁面から続く白と水色の編み地">川に見立てた編み地。</Evidence><figure><video controls playsInline preload="none" poster={`${asset}flower-poster.jpg`} aria-label="編み花の動作記録。約10秒・音声なし"><source src={`${asset}flower-study.mp4`} type="video/mp4"/>動画を再生できません。</video><figcaption>編み花の動作記録。編み物と機構の制作：共同制作者。</figcaption><a className="knitted-inline-link" href={`${asset}flower-study.mp4`} target="_blank" rel="noreferrer">動画を別タブで開く ↗</a></figure></div></section>
<section className="wrap section-grid section-space" id="reflection"><Label n="06">REFLECTION / NEXT QUESTION</Label><div><h2>素材を確かめながら、<br/>表現を考え直す。</h2><p className="body-copy">編み花では、糸の伸びなどが動きの伝わり方に関わっているのではないかと考えました。意図との差を調整すべき課題として捉えると同時に、その予想外の動き自体を表現に使える可能性にも気づきました。</p><p className="body-copy"><strong>狙いどおりに動かすための検証と、素材から生まれた変化を表現の手がかりにすること。</strong>今後は小さな試作で糸・編み方・張り方を比較しながら、その両方を確かめたいと考えています。</p><h3 className="study-subheading">感覚的な質を、設計できるものにする。</h3><p className="body-copy">柔らかい、張っている、しなる、ほどける。人は素材を、形や色だけでなく、そこから立ち上がる「感覚的な質」として捉えています。</p><p className="body-copy">今回の探索では、編み物の張力、伸縮、たわみ、編み目の開閉を、<strong>感覚やInteractionをつくるためのDesign Material</strong>として扱うことを試みました。</p><p className="study-statement">情報を伝えるために新しい画面を増やすのではなく、暮らしの中にある素材そのものが穏やかに変化し、気配や状態を伝える。</p><p className="body-copy">今回、人がその変化から何を感じ、何を読み取るかまでは検証していません。素材の変化を確かめることに加えて、それがどのような体験につながるかを探りたいと考えています。</p><p className="body-copy">現在は、この関心を映像・音・振動・動きにも広げています。人が感じる質を、選び、比較し、調整できる設計方法を探ることが、現在の研究関心です。</p><p className="study-closing">How can perceptual qualities<br/><em>become designable?</em></p></div></section>
<section className="credits wrap section-grid" id="credits"><Label n="07">ROLE / CREDITS</Label><div><div className="credits-heading"><h2>私の担当</h2><span>Concept / Direction / Review</span></div><ul>{roles.map((role,i)=><li key={role}><span>0{i+1}</span>{role}</li>)}</ul><h3 className="study-subheading">共同制作者</h3><dl className="knitted-collaborators"><div><dt>デザイン・スケジュール進行</dt><dd>koichi ishi</dd></div><div><dt>ニッター</dt><dd>miq</dd></div><div><dt>テクニカル</dt><dd>shuhey koyama</dd></div></dl><p className="credit-note">展示は4人による共同制作の成果です。編み物の制作、スケッチの描画、機構・システムの設計と実装は共同制作者が担当しました。</p></div></section><section className="project-switch wrap"><span className="eyebrow">NEXT PROJECT / 04</span><a href="/ryusei-wave"><span>Ryusei Wave</span><span aria-hidden="true">↗</span></a><p>星にも、魚の群れにも見える波。</p></section><ProjectNav current="/nnamuimonyo"/></main><footer className="wrap"><a className="footer-title" href="/knitted-vj-system">Knitted <em>VJ System</em><span aria-hidden="true">↗</span></a><div><span>PREVIOUS PROJECT / 02</span><a href="#top">ページの先頭へ ↑</a></div></footer></div>}
